import Spain from "../icons/Spain.astro";
import Germany from "../icons/Germany.astro";
import UnitedStates from "../icons/UnitedStates.astro";

interface Blog {
  slug: string;
  metaTitle: string;
  metaDescription: string;
  title: string;
  description: string;
  date: string;
  country: string;
  iconCountry: any;
  mainImage: string;
  images: {
    label?: string[];
    src: string[];
    description: string[];
  }[];
}

const BLOGS: Blog[] = [
  {
    slug: "rodaje-pelicula-knight-and-day",
    metaTitle:
      "Rodaje de Knight and Day con Tom Cruise y Cameron Diaz | Chef Armando Rivera",
    metaDescription:
      "Armando Rivera, chef del catering Rafael, participó en el rodaje de Knight and Day en Austria y Sevilla. Su colaboración destacó la cocina española en una producción de alto nivel junto a Tom Cruise, Cameron Diaz y el director James Mangold.",
    title: "Rodaje de pelicula Knight and day con Tom cruise y Cameron Diaz",
    description:
      "Durante el rodaje de Knight and Day, participé como chef del equipo de catering Rafael de Cine, brindando servicios culinarios de alta calidad para una mega producción internacional. La filmación se realizó entre Austria y Sevilla, con la presencia de los reconocidos actores Tom Cruise y Cameron Diaz, además del director James Mangold. Nuestra labor consistió en garantizar una experiencia para el elenco y equipo de producción, la cocina española fue protagonista, destacándose y aportando un valor cultural y sensorial al proyecto cinematográfico.",
    date: "2009",
    country: "Austria y España",
    iconCountry: Spain,
    mainImage:
      "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279002/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-09_w8uvxl.jpg",
    images: [
      {
        src: [
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278998/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-000_st526y.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278998/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-00_rgl6yz.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278999/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-02_ze6lmv.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278999/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-03_qwt8pc.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279000/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-04_fb29fg.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279000/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-05_paz5mp.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279001/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-06_myqwb0.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279001/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-07_s7i02l.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279002/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-08_uzwrww.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279002/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-09_w8uvxl.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279003/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-10_k6pnip.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279003/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-11_h8fkvi.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279004/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-12_uk4xa2.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279004/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-13_koznej.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279005/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-14_izbdqm.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279005/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-15_omcb1j.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279005/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-16_cpmowd.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279006/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-17_zdghwv.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279006/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-18_rm23if.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279007/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-19_fgedcb.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279007/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-20_u41e4f.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279008/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-21_heuppp.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279008/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-22_dm3y56.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279009/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-23_o0acbb.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279009/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-24_p24qja.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279010/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-25_jaupds.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279010/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-26_jjkulz.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736279011/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-27_r53x76.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278993/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-28_a4jeei.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278995/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-29_qq7fzt.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278994/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-30_vfiofj.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278994/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-31_pclkup.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278994/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-32_oyfkpj.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278995/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-33_ro9auz.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278994/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-34_ls1xqe.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278995/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-35_mfy8uz.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278996/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-36_xy4we1.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278996/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-37_ezt7bz.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278996/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-38_agz6ka.jpg",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736278997/chef-armando-rivera/blog/sevilla-wichita/pelicula-wichita-austria-sevilla-39_hcmkqf.jpg",
        ],
        description: [
          "Basecamp del catering",
          "Fortaleza “festung Hohensalzbburg” en Salzburgo – Austria, punto de rodaje 01",
          "Fortaleza “festung Hohensalzbburg” en Salzburgo – Austria, punto de rodaje 02",
          "Fortaleza “Festung Hohensalzbburg” en Salzburgo – Austria, punto de rodaje 03",
          "Food truck Catering Rafael",
          "Una noche de grill 01",
          "Una noche de grill 02",
          "Una noche de grill 03",
          "Actores principales Cameron Diaz y Tom Cruise",
          "Con el actor Español Jordi Mollà",
          "En el cumpleaños del director James Mangold 01",
          "Cumpleaños del director James Mangold 02",
          "Con el equipo de Catering Rafael 01",
          "Con el equipo de Catering Rafael 02",
          "Con el equipo de Catering Rafael 03",
          "Con el equipo de Catering Rafael 04",
          "Con el equipo de Catering Rafael 05",
          "Con el equipo de Catering Rafael 06",
          "Con el equipo de Catering Rafael 07",
          "Con el equipo de Catering Rafael 08",
          "Recorriendo las calles de Salzburgo - Austria 01",
          "Recorriendo las calles de Salzburgo - Austria 02",
          "Recorriendo las calles de Salzburgo - Austria 03",
          "Recorriendo las calles de Salzburgo - Austria 04",
          "Recorriendo las calles de Salzburgo - Austria 05",
          "Comida de equipo de producción 01",
          "Comida de equipo de producción 02",
          "Noche de vinos calientes",
          "Rio Salzach en Salzburgo - Austria",
          "Tradicionales huevos de pascua en Austria",
          "En el bar de Perejil en Sevilla 01",
          "En el bar de Perejil en Sevilla 02",
          "En el bar de Perejil en Sevilla 03",
          "Dia de rodaje en Sevilla 01",
          "Dia de rodaje en Sevilla 02",
          "Parte del equipo de producción en Sevilla 01",
          "Parte del equipo de producción en Sevilla 02",
          "Buffet ¡Es hora de comer!",
          "Panorámicas de Sevilla 01",
          "Panorámicas de Sevilla 02",
        ],
      },
    ],
  },
  {
    slug: "alemania-hotel-richtershof",
    metaTitle: "Mi experiencia culinaria en Alemania: Hotel Richtershof | Chef Armando Rivera",
    metaDescription: "Explora mi experiencia culinaria en el Hotel Richtershof, Alemania. Un viaje de aprendizaje gastronómico en 2014, fusionando la cocina española con la alemana.",
    title: "Cocinando en Alemania: Mi experiencia en el Hotel Richtershof",
    description:
      "Buscando una nueva experiencia para adquirir conocimientos en una gastronomía diferente, viajé a Alemania en 2014. Fue mi primera vez en el país, trabajando en el Hotel Richtershof, ubicado en el pintoresco pueblo de Mülheim (Moselle), rodeado de viñedos y naturaleza. Durante mi estadía, conocí a muchas personas con las que creé un vínculo laboral y un equipo de trabajo profesional que me brindó la oportunidad de adquirir un mayor conocimiento en la gastronomía alemana.",
    date: "2014",
    country: "Alemania - Mülheim (Moselle)",
    iconCountry: Germany,
    mainImage:
      "https://res.cloudinary.com/docw5yqzl/image/upload/v1736456142/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-00_qvipvf.webp",
    images: [
      {
        src: [
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736456142/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-00_qvipvf.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455082/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-01_xlvtvf.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455082/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-02_gqhonr.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455082/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-03_avhh0x.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455083/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-04_s5gwzr.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455083/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-05_tmptzo.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455084/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-06_leiosc.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455084/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-07_rw0ae4.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455085/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-08_j8hbzr.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455087/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-09_g7rrpt.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455086/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-10_sh4104.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455086/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-11_bu46qu.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455088/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-12_yhhbwu.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455088/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-13_pnecyy.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455089/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-14_zhtpah.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455092/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-15_g6fuk5.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455090/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-16_x6y5ab.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455090/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-17_geolw9.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455092/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-18_fhdkg7.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455092/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-19_uulfzn.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455093/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-20_qcnlnb.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455093/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-21_yhg87t.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455094/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-22_vzjd7i.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455095/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-23_kunjbj.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455095/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-24_txj9nr.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455096/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-25_r6bltp.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455097/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-26_kw2jmw.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455097/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-27_zlyp54.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455098/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-28_bntxyc.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455099/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-29_sohfk9.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455099/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-30_ivjie9.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455100/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-31_nphvav.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455101/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-32_ka2jd7.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455101/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-33_w1nnv5.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455102/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-34_ibeblb.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455103/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-35_jujtuk.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455103/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-36_d0ublx.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455104/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-37_kwadvl.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455105/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-38_abrv0z.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455105/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-39_q1qsgy.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455106/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-40_xlgoea.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455106/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-41_uxyvnr.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455107/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-42_stwxhq.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455108/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-43_rtkapo.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455109/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-44_g2qrbk.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455109/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-45_ixiwft.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455110/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-46_vxxjol.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455111/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-47_n94lor.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455111/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-48_wbzrev.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455112/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-49_dhllsk.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455112/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-50_dgk9ix.webp",
          "https://res.cloudinary.com/docw5yqzl/image/upload/v1736455113/chef-armando-rivera/blog/alemania/alemania-hotel-richtershof-51_vtieyx.webp",
        ],
        description: [
          "Mi primer día en el hotel Richtershof",
          "Empezando el dia con entusiasmo",
          "Preparando una sopa invernal de buey de mar 01",
          "Preparando una sopa invernal de buey de mar 02",
          "Preparando una sopa invernal de buey de mar 03",
          "Guarniciones de nuestros platos fuertes ",
          "La cocinas de Richtershof listaS para empezar el día 01",
          "La cocinas de Richtershof listaS para empezar el día 02",
          "Un exquisito pudin de coco 01",
          "Un exquisito pudin de coco 02",
          "Fusionando la gastronomía mediterránea",
          "Tapas españolas",
          "Preparando un arroz con bogavante",
          "Croquetas de ibéricos",
          "Con David en su cocina ",
          "Buenos momentos con mis compañeros abravick, Lukas, Javi",
          "After work con el equipo de cocina",
          "Mis locuras en la cocina 01",
          "Mis locuras en la cocina 02",
          "Mis locuras en la cocina 03",
          "Una foto entre fogones 01",
          "Una foto entre fogones 02",
          "Señores Preuß preparando una paella española",
          "En las bodegas del hotel 01",
          "En las bodegas del hotel 02",
          "Con mi compi Claudio",
          "Seleccionando productos fresco",
          "Nuestras creaciones 01",
          "Nuestras creaciones 02",
          "Nuestras creaciones 03",
          "Nuestras creaciones 04",
          "Nuestras creaciones 05",
          "Nuestras creaciones 06",
          "Nuestras creaciones 07",
          "Nuestras creaciones 08",
          "Nuestras creaciones 09",
          "Nuestras creaciones 10",
          "Nuestras creaciones 11",
          "Nuestras creaciones 12",
          "Nuestras creaciones 13",
          "Nuestras creaciones 14",
          "Nuestras creaciones 15",
          "Dia de relax",
          "De paseo en bicicleta 01",
          "De paseo en bicicleta 02",
          "Conociendo pueblos alemanes 01",
          "Conociendo pueblos alemanes 02",
          "Conociendo pueblos alemanes 03",
          "Conociendo pueblos alemanes 04",
          "Lindas panorámicas 01",
          "Lindas panorámicas 02",
          "Bonita arquitectura",
        ],
      },
    ],
  },
];

export default BLOGS;
